INSERT INTO B_ACCOUNT(ACCOUNT_IDENT , BALANCE )  values (1 , 0.0);
INSERT INTO B_CUSTOMER(CUSTOMER_IDENT , NOM , PRENOM , DATE_NAISSANCE, ACCOUNT_FK) values (1, 'ELMADKOURI','YOUNESS','1990-02-02',1);